import { cp, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const out = resolve(root, 'dist');
await mkdir(out, { recursive: true });
await cp(resolve(root, 'public'), out, { recursive: true, filter: (path) => !path.endsWith('.onnx') });
await cp(resolve(root, 'src'), resolve(out, 'src'), { recursive: true });
await cp(resolve(root, 'index.html'), resolve(out, 'index.html'));
await cp(resolve(root, 'licenses'), resolve(out, 'licenses'), { recursive: true });
console.log('Static site written to dist/. Model weights are intentionally excluded; users can select their downloaded model.');
